import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'core/constants/routes.dart';
import 'core/theme/app_theme.dart';
import 'providers/app_providers.dart';

// This file is generated by flutter gen-l10n
// Replace with actual generated import once built:
// import 'core/localization/generated/app_localizations.dart';

class ToBestApp extends ConsumerWidget {
  const ToBestApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final settings = ref.watch(appSettingsProvider);
    final router = ref.watch(routerProvider);

    final theme = AppTheme.buildTheme(settings.themeType, settings.accentColor);
    final lightTheme = AppTheme.buildTheme(AppThemeType.light, settings.accentColor);

    return MaterialApp.router(
      title: 'TO Best',
      debugShowCheckedModeBanner: false,
      theme: lightTheme,
      darkTheme: theme,
      themeMode: _resolveThemeMode(settings.themeType),
      routerConfig: router,
      locale: settings.locale,
      supportedLocales: const [
        Locale('ar'),
        Locale('en'),
      ],
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      builder: (context, child) {
        return Directionality(
          textDirection: settings.textDirection,
          child: child ?? const SizedBox.shrink(),
        );
      },
    );
  }

  ThemeMode _resolveThemeMode(AppThemeType type) {
    switch (type) {
      case AppThemeType.light:
        return ThemeMode.light;
      case AppThemeType.dark:
      case AppThemeType.luxury:
      case AppThemeType.sports:
        return ThemeMode.dark;
    }
  }
}
